version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The PAIR_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     PAIR_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:

  zipkin:
    ports:
      - "5411:9411"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5001:80"
      - "50001:50001"

  basket-api-dapr:
    command: ["./daprd",
      "-app-id", "basket-api",
      "-app-port", "80",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/configuration/:/configuration"

  web-httpaggregator-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5002:80"
      - "50002:50002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  web-httpaggregator-api-dapr:
    command: ["./daprd",
      "-app-id", "web-httpaggregator-api",
      "-app-port", "80",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/configuration/:/configuration"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"